//! C header generation.
//!
//! Generated from the same `ResolvedAbiSurface` the manifest is, so the two
//! cannot describe different things. The shape is frozen in section 4.16 and
//! checked against `examples/v4_contract_header/demo.h`.

use fol_abi::{AbiErrorContract, AbiType, AbiTypeId, AbiTypeTable, ResolvedAbiSurface};

/// The include guard for an artifact, per section 4.16.
///
/// `FOL_` prefixed and uppercased with non-alphanumerics replaced, so a short
/// artifact name cannot collide with a consumer's own guard.
pub fn include_guard(artifact: &str) -> String {
    let mut guard = String::from("FOL_");
    for ch in artifact.chars() {
        if ch.is_ascii_alphanumeric() {
            guard.push(ch.to_ascii_uppercase());
        } else {
            guard.push('_');
        }
    }
    guard.push_str("_H");
    guard
}

fn c_type(table: &AbiTypeTable, id: AbiTypeId) -> String {
    match table.get(id) {
        Some(AbiType::Scalar(scalar)) => scalar.c_type(),
        Some(AbiType::Void) => "void".to_string(),
        _ => "void".to_string(),
    }
}

/// Render the complete header for one surface.
pub fn render_header(surface: &ResolvedAbiSurface) -> String {
    let guard = include_guard(&surface.artifact);
    let table = &surface.interface.types;
    let mut out = String::new();

    out.push_str(&format!(
        "/* {}.h -- generated by FOL. Do not edit.\n *\n * ABI {}.{} for {}.\n */\n\n",
        surface.artifact,
        surface.major,
        surface.minor,
        surface.interface.target.rust_target_triple()
    ));
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    out.push_str(
        "/* Every exported FOL routine returns this. Ordinary results travel through out\n \
         * parameters, so an infallible-looking function still has a panic and\n \
         * validation channel. */\n",
    );
    out.push_str("typedef int32_t fol_status_t;\n\n");
    out.push_str(
        "/* Only 0 and 1 are valid. Imports validate. */\ntypedef uint8_t fol_bool_t;\n\n",
    );
    out.push_str(
        "/* A Unicode scalar value. Imports validate. */\ntypedef uint32_t fol_char_t;\n\n",
    );

    for (name, value, description) in fol_abi::STATUS_VALUES {
        // Negative macros are parenthesized: `x == -1` and `x == (-1)` differ
        // once the macro is pasted into a larger expression.
        let rendered = if *value < 0 {
            format!("({value})")
        } else {
            value.to_string()
        };
        out.push_str(&format!("/* {description} */\n#define {name} {rendered}\n"));
    }
    out.push('\n');

    out.push_str(
        "/* On any failure the success out values are left uninitialized. The caller\n \
         * must not read or free them. On FOL_STATUS_REPORT, and only then, the typed\n \
         * error out parameter is initialized. */\n\n",
    );

    // Sorted by symbol, matching the manifest's canonical ordering, so a
    // reordered source file does not produce a different header.
    let mut routines: Vec<_> = surface
        .interface
        .facing(fol_abi::AbiFacing::Export)
        .collect();
    routines.sort_by(|left, right| left.symbol.cmp(&right.symbol));

    for routine in routines {
        let mut params: Vec<String> = routine
            .parameters
            .iter()
            .map(|parameter| format!("{} {}", c_type(table, parameter.type_id), parameter.name))
            .collect();
        if !matches!(table.get(routine.result), Some(AbiType::Void)) {
            params.push(format!("{} *out_result", c_type(table, routine.result)));
        }
        if let AbiErrorContract::Recoverable { error_type } = &routine.error {
            params.push(format!("{} *out_error", c_type(table, *error_type)));
        }
        if params.is_empty() {
            params.push("void".to_string());
        }
        out.push_str(&format!(
            "/* {} */\nfol_status_t {}({});\n\n",
            routine.fol_path,
            routine.symbol,
            params.join(", ")
        ));
    }

    out.push_str("#ifdef __cplusplus\n} /* extern \"C\" */\n#endif\n\n");
    out.push_str(&format!("#endif /* {guard} */\n"));
    out
}
