name: release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - name: Checkout FOL
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: fol

      - name: Checkout PARC
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: fol-lang/parc
          ref: 0f52aeeeeec47a082c0d8a515130ee853aa1101d
          path: parc

      - name: Checkout LINC
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: fol-lang/linc
          ref: c874d5b0332249524422d9d08c35b3d4edd7e3fa
          path: linc

      - name: Checkout GERC
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: fol-lang/gerc
          ref: 000c1f6c12fba99f1a157267ee7db39d42bda8e3
          path: gerc

      - name: Compile and release
        id: compile
        uses: rust-build/rust-build.action@7d5b0c135ddb825f7692d4d2d75e598184d15cec # v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SRC_DIR: fol
          TOOLCHAIN_VERSION : stable
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: "zip tar.gz"
          # ARCHIVE_NAME: "roc_${{ matrix.target }}"
